# Generated by Django 5.2.13 on 2026-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "picture",
                    models.CharField(
                        default="https://platform.la.eater.com/wp-content/uploads/sites/26/chorus/uploads/chorus_asset/file/22764709/2021_06_24_Gril_TheGoat_005.jpg?quality=90&strip=all&crop=16.619412941961%2C0%2C66.761174116077%2C100&w=2400",
                        max_length=200,
                    ),
                ),
                ("cuisine", models.CharField(max_length=200)),
                ("rating", models.CharField()),
            ],
        ),
    ]
