# Generated by Django 5.1.1 on 2026-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.CharField(max_length=5),
        ),
    ]
