# Generated by Django 5.1.1 on 2026-05-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_restaurant_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "picture",
                    models.URLField(
                        default="https://cdn-icons-png.flaticon.com/512/1147/1147856.png"
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("is_veg", models.BooleanField(default=True)),
                (
                    "menu_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="delivery.restaurant",
                    ),
                ),
            ],
        ),
    ]
