# Generated by Django 5.1.1 on 2026-05-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="menu_items",
        ),
        migrations.AddField(
            model_name="item",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="delivery.restaurant",
            ),
            preserve_default=False,
        ),
    ]
